# Generated by Django 3.0.8 on 2020-07-28 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('symbol', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('type', models.CharField(choices=[('TRADE', 'Trade'), ('DIV', 'Dividend'), ('INT', 'Interest'), ('CG', 'Capital Gain Distribution'), ('CASH', 'Cash')], default='CASH', max_length=64)),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=16)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portvis.Security')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portvis.Security')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('DIV', 'Stock Dividend'), ('SPLIT', 'Split')], default='SPLIT', max_length=16)),
                ('value', models.DecimalField(decimal_places=1, max_digits=10)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portvis.Security')),
            ],
        ),
    ]
