# Generated by Django 3.0.8 on 2020-07-29 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portvis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='price',
            new_name='value',
        ),
    ]
