# Generated by Django 3.0.8 on 2020-07-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portvis', '0003_auto_20200729_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tstamp',
            field=models.DateField(),
        ),
    ]
