# Generated by Django 3.0.8 on 2020-07-31 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portvis', '0004_auto_20200729_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='close',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='action',
            name='value',
            field=models.DecimalField(decimal_places=1, max_digits=16),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.DecimalField(decimal_places=4, max_digits=16),
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('security', 'tstamp')},
        ),
    ]
